#!/bin/bash
set -e

echo "${INPUT_PROJECT}\n${INPUT_COMMIT}\n${INPUT_BRANCH}\n${INPUT_STATUS}\n${INPUT_ACTIONID}\n${INPUT_WEBHOOK}\n${HOME}\n${GITHUB_JOB}\n${GITHUB_REF}\n${GITHUB_SHA}\n${GITHUB_REPOSITORY}\n${GITHUB_REPOSITORY_OWNER}\n${GITHUB_RUN_ID}\n${GITHUB_RUN_NUMBER}\n${GITHUB_RETENTION_DAYS}\n${GITHUB_RUN_ATTEMPT}\n${GITHUB_ACTOR}\n${GITHUB_WORKFLOW}\n${GITHUB_HEAD_REF}\n${GITHUB_BASE_REF}\n${GITHUB_EVENT_NAME}\n${GITHUB_SERVER_URL}\n${GITHUB_API_URL}\n${GITHUB_GRAPHQL_URL}\n${GITHUB_REF_NAME}\n${GITHUB_REF_PROTECTED}\n${GITHUB_REF_TYPE}"

